# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-154486893-1'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Services', folder: 'pages', file: 'services.html'}
- {name: 'Blog', folder: 'pages', file: 'posts.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Research', folder: 'pages', file: 'research.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/mrjak318'}
- {icon: 'facebook', link: 'https://www.facebook.com/'}
- {icon: 'instagram', link: 'https://instagram.com/'}
- {icon: 'envelope', link: 'mailto:mrjak318@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
